trigger:
  - master 
    
pool: 
    vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
  - task: NuGetToolInstaller@1
    displayName: Configuration Source Project Nuget Tools Installation

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
    displayName: Configuration Source Project NuGetCommand

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\\" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
    displayName: Configuration Source Project Build

  - task: DotNetCoreCLI@2
    displayName: 'Configuration Source Project Package Application'
    inputs:
      commands: publish
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
      modifyOutputPath: false
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Configuration Source Project Publish Artifact'