trigger:
- main 

variables: 
    buildConfiguration: 'Release'
    
pool: 
    vmImage: 'ubuntu-latest'
    
steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '5.x'

- task: DotNetCoreCLI@2
    displayName: 'Build Application'
    inputs:
        commands: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.BinariesDirectory)/$(Build.BuildId)'
        modifyOutputPath: false

- task: PublishBuildArtifact@1
    displayName: 'Publish Web Artifact'
    inputs:
        pathToPublish: '$(Build.BinariesDirectory)/$(Build.BuildId)'
        ArtifactName: 'drop-$(Build.BuildId)'
        publishLocation: 'Container'