trigger:
  - master 

variables: 
    buildConfiguration: 'Release'
    
pool: 
    vmImage: 'windows-latest'
    
steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '6.x'

  - task: DotNetCoreCLI@2
    displayName: 'Configuration Source Project Package Application'
    inputs:
      commands: publish
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
      modifyOutputPath: false
      zipAfterPublish: : true

  - task: PublishBuildArtifacts@1
    displayName: 'Configuration Source Project Publish Artifact'